import sys
import os
# Ensure app module is found. In container, app is at /app/app
sys.path.append('/app') 

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker
from app.models import Base, Case, Media, VideoSignature, Category, MediaCategory
from datetime import datetime

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    print("DATABASE_URL not set")
    sys.exit(1)

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)
db = SessionLocal()

def seed():
    try:
        # 1. Create Case
        print("Creating case...")
        case = Case(name="UI Test Case", description="Generated by Sisyphus for UI testing")
        db.add(case)
        db.commit()
        db.refresh(case)
        print(f"Created Case: {case.id}")

        # 2. Create Video Media with Signature
        print("Creating video...")
        video = Media(
            case_id=case.id,
            original_filename="test_video.mp4",
            stored_filename="uuid_video.mp4",
            file_path="cases/1/uuid_video.mp4",
            file_size=1024000,
            mime_type="video/mp4",
            status="completed"
        )
        db.add(video)
        db.commit()
        db.refresh(video)

        sig = VideoSignature(
            media_id=video.id,
            temporal_signature="deadbeef12345678", # Mock sig
            audio_fingerprint="audio_hash_mock_123",
            keyframe_hashes="hash1,hash2",
            color_histogram=b"mock_binary"
        )
        db.add(sig)
        
        # 3. Create Image Media with GPS (for Map)
        print("Creating image with GPS...")
        image = Media(
            case_id=case.id,
            original_filename="geo_image.jpg",
            stored_filename="uuid_image.jpg",
            file_path="cases/1/uuid_image.jpg",
            file_size=500000,
            mime_type="image/jpeg",
            status="completed",
            gps_lat=51.5074,
            gps_lon=-0.1278
        )
        db.add(image)
        db.commit() # Get ID
        db.refresh(image)
        
        # 4. Create Category and Link
        print("Creating category...")
        # Check if category exists
        cat = db.query(Category).filter_by(name="Evidence").first()
        if not cat:
            cat = Category(name="Evidence", color="#ff0000", is_system=True)
            db.add(cat)
            db.commit()
            db.refresh(cat)
        
        mc = MediaCategory(media_id=image.id, category_id=cat.id, source="user", upvotes=1)
        db.add(mc)

        db.commit()
        print("Seeding complete.")
    except Exception as e:
        print(f"Error seeding: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed()
